name = "calibration_lines"

vertex="""
        #version 150

        in vec2 position;

        void main() {
            gl_Position = vec4(position, 0.0, 1.0);
        }
        """

fragment="""
        #version 150

        out vec4 color;

        void main() {
            color = vec4(1.0, 1.0, 1.0, 1.0); // White color for the line
        }
        """
