name = "calibration"

vertex="""
     #version 330

      in vec2 position;
      in vec2 uv;
      
      out vec2 uv_coords;
      void main() {
          uv_coords = uv;
          gl_Position = vec4(position, 0.0, 1.0);
      }
     """ 

fragment="""
      #version 330  

      in vec2 uv_coords;
      uniform sampler2D tex;

      out vec4 color;
      
      void main(){ 
         vec4 val = texture(tex, vec2(uv_coords.x, uv_coords.y));   
          color =  val;
      }
      """
