name = "skull_game_particle_shader"

vertex="""
     #version 330

      in vec2 position;
      in vec2 uv;
      in vec3 color;
      in float blend_value;
      
      out vec2 v_uv_coords;
      out vec3 v_color;

      void main() {
          v_uv_coords = uv;
          v_color = color;
          gl_Position = vec4(position, 0.0, 1.0);
      }
     """ 

fragment="""
      #version 330  

      in vec2 v_uv_coords;
      in vec3 v_color;

      out vec4 color;
      
      void main(){ 
           float blend_x = (1.0 - abs(v_uv_coords.x));
           float blend_y = (1.0 - abs(v_uv_coords.y));
           float blend = 0.4*(blend_x*blend_x + blend_y*blend_y);
           color =  vec4(v_color,blend);
         }
      """
