
name = "skull_game_moon_shader"

vertex="""
     #version 330

      in vec2 position;
      in vec2 uv;
      in float blend_value;
      in float texture_id;
      
      out vec2 v_uv_coords;
      out float v_blend_value;
      out float v_texture_id;

      void main() {
          v_uv_coords = uv;
          v_blend_value = blend_value;
          v_texture_id = texture_id;
          gl_Position = vec4(position, 0.0, 1.0);
      }
     """ 

fragment="""
      #version 330  

      in vec2 v_uv_coords;
      in vec3 v_color;
      in float v_texture_id;

      uniform sampler2DArray moon_textures;

      out float v_blend_value;
      out vec4 color;
      
      void main(){ 
           float blend_x = (1.0 - abs(v_uv_coords.x));
           float blend_y = (1.0 - abs(v_uv_coords.y));
           float blend = 0.2*v_blend_value*(blend_x*blend_x + blend_y*blend_y);
           vec4 moon_tex = texture(moon_textures, vec3(v_uv_coords, v_texture_id));
           vec4 mask_tex = texture(moon_textures, vec3(v_uv_coords, 0.0));
           color =  vec4(mask_tex.xyz,1.0);
         }
      """
