name = "skull_game_particle_shader"

vertex="""
     #version 330

      in vec2 position;
      in vec2 uv;
      in vec3 color;
      in float blend_value;
      
      out vec2 v_uv_coords;
      out vec3 v_color;
      out float v_blenc_value;

      void main() {
          v_uv_coords = uv;
          v_blenc_value = blend_value;
          v_color = color;
          gl_Position = vec4(position, 0.0, 1.0);
      }
     """ 

fragment="""
      #version 330  

      in vec2 v_uv_coords;
      in vec3 v_color;
      in float v_blenc_value;

      out vec4 color;
      
      void main(){ 
        float x = v_uv_coords.x;
        float y = v_uv_coords.y;
        float r = sqrt(x*x+y*y);

        float blend = 1.0-smoothstep(0.1,0.8,r);
        color =  vec4(v_color,blend*blend*v_blenc_value);
         }
      """
