[package]
name = "platos_beamer"
version = "0.1.0"
edition = "2024"

[dependencies]
glint = "6.3.4"
opencv ={version = "0.95.1", features=["clang-runtime"]}
serde = {version = "1.0.219", features= ["derive"]}
toml = "0.9.5"
winit = "0.30.12"
