[package]
name = "platos_beamer"
version = "0.1.0"
edition = "2024"

[dependencies]
glium = "0.36.0"
image = "0.25.8"
noise = "0.9.0"
opencv ={version = "0.95.1", features=["clang-runtime"]}
rand = "0.9.2"
rodio = "0.21.1"
serde = {version = "1.0.219", features= ["derive"]}
toml = "0.9.5"
