game_type= "SkullGame"

["camera_config"]
device_index=0

["background_subtractor_config"]
subtractor_type = "Naive"

["minimap_config"]
show = true
position = [0.4,0.4]
dims     = [0.5,0.5]

["key_config"]
quit_key = "q"
reset_key = "r"
toggle_minimap_key ="m"

