#game_type= "CalibrationGame"
game_type= "SkullGame"
#game_type= "IdentityGame"

[camera_config]
device_index=0

[background_subtractor_config]
subtractor_type = "OpticalFlow"
settings_path = "src/bg_subtract/config.toml"

[minimap_config]
show = "Hide"
position = [0.4,0.4]
dims     = [0.5,0.5]

[key_config]
quit_key = "q"
reset_key = "r"
toggle_minimap_key ="m"

[sound_config]
master_volume = 1.0
sfx_volume = 0.5
music_volume = 0.3
