spawn_rate = 2.5
crystal_position = [0.0,-0.5]
max_number = 500
scale_speed   = 0.1
move_speed    = 0.1
start_scale = 0.11
hitable_from = 0.4
max_scale = 0.6
threshold = 0.1
x_start = [-0.5,0.5]
y_start = [-0.5,0.5]
rot     = [-0.4,0.4]
skull_shader = "src/shaders/skull_game_skull.toml"
particle_shader="src/shaders/skull_game_particle.toml"
mask_color = [130,70,200]
skull_alive_textures = [
    "assets/skull/skull_0.png",
    "assets/skull/skull_1.png",
    "assets/skull/skull_2.png",
    "assets/skull/skull_3.png",
]
skull_killed_textures= [
    "assets/skull/skull_kill_0.png",
    "assets/skull/skull_kill_1.png",
]

