shader_settings = [
    [
        "skull_program",
        "src/shaders/skull_game_skull.toml",
    ],
    [
        "particle_program",
        "src/shaders/skull_game_particle.toml",
    ],
    [
        "live_program",
        "src/shaders/skull_game_live.toml",
    ],
    [
        "corona_program",
        "src/shaders/skull_game_corona.toml",
    ],
    [
        "moon_program",
        "src/shaders/skull_game_moon.toml",
    ],
    [
        "victory_program",
        "src/shaders/skull_game_victory.toml",
    ],
]

sound_settings = [
    [
        "skull_kill_sound_1",
        "assets/sound/killed_1.wav",
    ],
    [
        "skull_kill_sound_2",
        "assets/sound/killed_2.wav",
    ],
    [
        "skull_kill_sound_3",
        "assets/sound/killed_3.wav",
    ],
    [
        "skull_escaped_sound_1",
        "assets/sound/escape_1.wav",
    ], 
    [
        "skull_escaped_sound_2",
        "assets/sound/escape_2.wav",
    ],
    [
        "skull_escaped_sound_3",
        "assets/sound/escape_3.wav",
    ],
    [
        "skull_escaped_sound_4",
        "assets/sound/escape_4.wav",
    ],
    [
        "intermission",
        "assets/sound/intermission.mp3",
    ],
    [
        "intermission",
        "assets/sound/intermission.mp3",
    ],
    [
        "go",
        "assets/sound/go.wav",
    ],
    [
        "finish",
        "assets/sound/finish.wav",
    ],
    [
        "bgm",
        "assets/sound/music.mp3",
    ],
]

number_of_rounds        = 2
number_of_kill_sounds   = 3
number_of_escape_sounds = 4

[texture_settings]
texture_arrays = [
    [
        "skull_alive_textures",
        [
            "assets/skull/skull_0.png",
            "assets/skull/skull_1.png",
            "assets/skull/skull_2.png",
            "assets/skull/skull_3.png",
        ],
    ],
    [
        "skull_killed_textures",
        [
            "assets/skull/skull_kill_0.png",
            "assets/skull/skull_kill_1.png",
        ],
    ],
]

textures = [
    [
        "victory_texture",
        "assets/victory.png",
    ],
    [
        "clouds",
        "assets/clouds/noise_1.png",
    ],
    [
        "clouds2",
        "assets/clouds/noise_2.png",
    ],
    [
        "sky",
        "assets/clouds/sky.jpg",
    ],
    [
        "moon",
        "assets/moon/moon_mask.png",
    ],
    [
        "moon_texture",
        "assets/moon/moon_texture.png",
    ]
]
mask_color = [130, 70, 200]

[skull_settings]
    spawn_rate = 1.0
    max_number = 50
    scale_speed = 0.06
    move_speed = 0.5
    start_scale = 0.1
    hitable_from = 0.1
    max_scale = 0.3
    threshold = 0.1
    x_start = [-0.5, 0.5]
    y_start = [-0.5, 0.5]
    rot = [-0.4, 0.4]
    erratic_movement = 4.0

[moon_settings]
    starting_life=20
    position=[0.0,0.35]
    max_position= [0.0, 0.7]
    scale=[0.1,0.17]

    color_overlay = [
        [1.0, 0.5, 0.0],
        [1.0, 0.0, 0.0],
        [1.0, 1.0, 1.0],
    ]

    corona_color = [
        [1.0, 1.0, 0.0],
        [1.0, 1.0, 0.0],
        [1.0, 1.0, 1.0],
    ]

[key_settings]
  start_key = "s"
  easy_mode_key = "1"
  normal_mode_key = "2"

[particle_settings.escaped] 
    scale=0.04
    color=[1.0, 0.0, 0.0]
    opacity=0.75
    initial_velocity = 1.0
    number= 1200

[particle_settings.killed]
    scale=0.02
    color=[0.0, 1.0, 1.0]
    opacity=0.75
    initial_velocity = 1.7
    number= 2000

[particle_settings.visualization]
    scale=0.01
    color=[0.0, 1.0, 1.0]
    opacity=1.0
    initial_velocity = 1.0
    number= 2000

[difficultiy_settings.easy]
    player_damage: 5
    escape_penalty: 0

[difficultiy_settings.normal]
    player_damage: 1
    escape_penalty: 1