spawn_rate = 1.5
crystal_position = [0.0,0.0]
max_number = 5
scale_speed   = 0.1
move_speed    = 0.1
start_scale = 0.1
hitable_from = 0.7
max_scale = 1.0
x_start = [-0.5,0.5]
y_start = [0.0,0.2]
rot     = [-0.1,0.1]